### ISSUE TITLE
Unable to locate package ipconfig

### ISSUE THREAD

**Issue by bernardolm** [zanaca/docker-dns#21]
When `Fetching origin`, installation fails while trying to install the _ipconfig_ package. It's referenced in `requirements.apt`.

```shell
Fetching origin
E: Unable to locate package ipconfig
make: *** [install-dependencies] Error 100
/usr/lib/node_modules/hudctl/node_modules/sql.js/js/sql.js:3
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!

Error: Command failed: make install tag=hu/ns0 name=ns0 tld=hud
E: Unable to locate package ipconfig
make: *** [install-dependencies] Error 100

    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at Object.str [as start] (/usr/lib/node_modules/hudctl/src/app.js:410:13)
    at Object.<anonymous> (/usr/lib/node_modules/hudctl/cli.js:182:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Comment by zanaca** [comment]
Resolved with commit 1bb44999aeef9f29f3783c9d14fe08b0f51b192f
